### ISSUE TITLE
feat. req.: separate interface for study-level data 

### ISSUE THREAD

**Issue by turbomam** [Public-Health-Bioinformatics/covid19ValidationGrid#211]
I have really been enjoying experimenting with DataHarmonizer and I have appreciated our meetings. I can't remember whether we discussed this yet...

Could there be some user interface component, separate from the existing HOT sheet for sample metadata, that captures study level data? I can even imagine it as a static form. I don't imagine it requiring multiple rows.

- PI name, email, ORCID, etc.
- PI's chosen study ID
- cross references to public identifiers, like DOIs, NCBI BioProjects, etc.?
- etc.?

Then, the user shouldn't have to enter any of that information in the existing sample metadata sheet, but upon save or export, those values would be pasted in as constants values in additional columns.

I guess we could just start out with columns for those study parameters, and the user would just fill out one row and copy/paste across the other rows.

Another solution would be just inserting a "part_of" column into the existing sample metadata sheet and then populating the study ID. It would be cool if we could export this imaginary study metadata and the sample metadata into two JSON files. See #209

**Comment by dehays** [comment]
@turbomam Managing references between attributes of different classes / sheets - might be something more easily supported by interfaces for some server side persistence and validation.    So you could have a study template and different flavors of biosample templates.  Save (POST) the study.  Then use a validation to validate on an instance of biosample to check that the study identifiers map to existing study records.  This begins to define a workflow (create a study and then create biosamples that refer to that study) which is more application use case specific than what DataHarmonizer needs to do itself.

**Comment by ddooley** [comment]
We're turning to scoping this functionality design again now due to some pressing needs for an AMR project. Emma has asked for:

`the ability to handle one-to-many relationships between samples, isolates, sequences and assay profiles using sample, isolate, sequence identifiers as keys. For example, a sample may be collected on a certain date, in a certain place, and be associated with a sample type. If several colonies are isolated from the sample, the identical sample information must be entered over and over again for the different isolates. If different sequences are produced from the same isolate, the identical isolate and sample information must be entered over and over again. Modularization and auto-fill functions will greatly help to reduce the need for repetitive data entry. `

Now that DataHarmonizer runs via the browser API, it should be easier to present users with components where a main DH table can link records to a view/edit form for 1-many records.  The design question that follows is what data format can we store such edits in?  @dehays as you say it could be server side esp. if that's where the 1-many relations are stored/managed.  But we're also interested in maintaining a stand-alone browser version too, and so wondering about a single file multi-table data format, and so thought right away of SQLite (though I'm not sure if it can be loaded without a webserver).  Are there any other formats we should consider for stand-alone operation?
