### ISSUE TITLE
Passage number 'not applicable' not recognized as valid

### ISSUE THREAD

**Issue by cmrn-rhi** [Public-Health-Bioinformatics/covid19ValidationGrid#49]
Passage number guidance states `If not passaged, put "not applicable"` but the validator considers this input invalid.

**Comment by ivansg44** [comment]
The reason it is invalid is because we have designated the passage number field as datatype `"xs:nonNegativeInteger"`. So it only validates integers greater than zero.

But really, the reference guide states this field is a combination of two datatypes: `"xs:nonNegativeInteger"` and `"select"`. It should validate integers greater than zero, and also validate against a vocabulary containing the value `"not applicable"`. But we haven't implemented a way to have multiple datatypes for a field.

A quick fix would be to allow default values that fields accept if validation otherwise fails. An even quicker fix would be to remove "not applicable" from the reference guide for `"passage number"`, and acknowledge the limitations of our current design. But that's lame.

Default values would be quick to implement, and just a simple extra check in one of our functions, but if we design a system that actually assigns multiple datatypes to fields, and validates them correctly, users could actually see the default values as they type in a picklist, and we could also make the grid much more flexible to all sorts of stakeholder needs for future fields. So we should consider implementing multiple datatypes for a single field.

Here's how we could do it:

1. In `data.js`, change the value of `datatype` keys to arrays.
Fields with one datatype like `"host age"` become `"datatype": ["xs:decimal"]`.
Fields with multiple datatypes like `"passage number"` become `"datatype": ["xs:decimal", "select"]`.
2. In `main.js`, change all `datatype === ...` expressions to `datatype.includes(...)`.
3. In the `main.js` function [`getInvalidCells`](https://github.com/Public-Health-Bioinformatics/covid19ValidationGrid/blob/8ba436d757aeafa03fe9fa9f70e87b4aa93ea73d/main.js#L604), you'll need to change the control structure somewhat. Idea:
- Change the initial value of `valid` to `false`
- Change all the `else if` statements to `if` statements
- Only enter each `if` statement if `valid` is still false
- Add an `if` statement near the top for `xs:token` that always turns `valid` true

**But there's one big roadblock**:

`xs:date`, `select` and `multiple` have their own, unique editors that are not compatible.
The solution to that would be to use the editor of the first datatype listed, but validate the entered values against every datatype listed.


With regards to the google sheet we compile `data.js` from, we could delimit values under `datatype` using semicolons, and @damion could adjust `make_data.py` accordingly.

**Comment by ddooley** [comment]
On the face of it, its true, a field like that is exhibiting two datatypes in one (multiplexing).  We'll need that detail, but I would gravitate towards having a datatype field focused on the measurable, and a second datatype field for the metadata.  The metadata one could be checked for validity first, and if satisfied, return, otherwise the measurable datatype is checked.  This would help keep things simple for downstream data processing.

**Comment by ddooley** [comment]
I think the metadata datatype is probably always a select, so its just a question of which values are in that select list.  Could add a field in covid19 vocab called "metadata" that just contains the permissible values (e.g.semicolon list).  Solves the problem of having metadata selections burried within selection lists too. Its just that those selections have to be added to field select lists during app setup.

**Comment by ivansg44** [comment]
> This would help keep things simple for downstream data processing.

How so?

**Comment by ddooley** [comment]
Downstream processors can distinguish the metadata to carve off field content, and pass the measurable content on for processing. They'll know the "official" datatype of the field.

**Comment by ddooley** [comment]
Actually not "metadata" column.  Better named something like "field status" column.

**Comment by ddooley** [comment]
How about I revise the covid19 Vocab to put those values into metadata column and echo that into data.js .  App itself should merge metadata choices at bottom of select lists. The remaining problem is the date field though with its selector.

**Comment by ivansg44** [comment]
I see, but what if there's more than one official datatype? Then we're back to this multiplexing business for a different field. We need something extendable for validation, like linear steps through an array of types, rather than adding different fields with varying logic.

Is it possible we have oversimplified things by using `"datatype"` to declare our cell editor, validator and "official datatype"?

What if `"datatype"` simply marked our "official datatype"? And then we had separate fields for `"editor"`, and `"validateAgainst"`? Three fields referring to three distinct things: actual datatype, editor and validator.

**Comment by ivansg44** [comment]
I think this warrants further discussion before we make a move on this. Let’s get everyone together and come up with a solution for this, and the tagging thing, before we revise anything.

**Comment by ddooley** [comment]
Agreed.  I agree also that the app may need validator and editing call for each data type. The vocabulary file doesn't need to manage that. There are lots of multi-component datatypes - things that have parts, and this includes spreadsheet columns whose textual content can be parsed further.  Even assuming a non-ontological approach to this structured data, its ok to have more complex data types packed into one field but each one should have a name (e.g "select" or "lat_long") to invoke a handler for it.
But the field status dimension is a level above whatever specific atomic or component data type is being handled by the app.
